server:
  port: 8080

spring:
  application:
    name: tilog-backend
  datasource:
    url: jdbc:mysql://localhost:3306/tilog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #  validate update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false